export { Login } from "./Login";
export { SignUp } from "./SignUp";
export { Profile } from "./Profile";
export { CommentScreen } from "./CommentScreen";
export { Home } from "./Home";
export { Search } from "./Search";
export { PictureFeed } from "./PictureFeed";
export { Notification } from "./Notification";
export { Configuration } from "../components/Configuration"